// One-off: download the Google Fonts the site uses (latin + latin-ext subsets only —
// covers DE/EN incl. umlauts) into src/assets/fonts/ and emit a self-hosted
// src/assets/css/fonts.css. Run once: node scripts/fetch-fonts.js  (or npm run fonts)
// Goal: no third-party font requests (perf: no render-blocking cross-origin fetch;
// privacy: no visitor IP sent to Google).
const fs = require("fs");
const path = require("path");

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300..600;1,9..144,300..600&family=Spectral:ital,wght@0,400;0,500;0,600;1,400&family=Inter:wght@400;500;600&display=swap";
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";
const KEEP = new Set(["latin", "latin-ext"]);

const FONT_DIR = path.join(__dirname, "..", "src", "assets", "fonts");
const CSS_OUT = path.join(__dirname, "..", "src", "assets", "css", "fonts.css");
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

(async () => {
  fs.mkdirSync(FONT_DIR, { recursive: true });
  const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m,
    out =
      "/* Self-hosted fonts (latin + latin-ext). Generated by scripts/fetch-fonts.js — do not edit by hand. */\n",
    count = 0,
    bytes = 0;
  const seen = new Set();
  while ((m = re.exec(css)) !== null) {
    const subset = m[1];
    if (!KEEP.has(subset)) continue;
    const body = m[2];
    const family = (body.match(/font-family:\s*'([^']+)'/) || [])[1];
    const style = (body.match(/font-style:\s*(\w+)/) || [])[1] || "normal";
    const weight = ((body.match(/font-weight:\s*([\d ]+)/) || [])[1] || "400").trim();
    const url = (body.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
    if (!family || !url) continue;
    const name = `${slug(family)}-${weight.replace(/ /g, "-")}-${style}-${subset}.woff2`;
    if (!seen.has(name)) {
      const buf = Buffer.from(
        await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer()
      );
      fs.writeFileSync(path.join(FONT_DIR, name), buf);
      seen.add(name);
      count++;
      bytes += buf.length;
    }
    const local = body.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(/assets/fonts/${name})`);
    out += `/* ${family} ${weight} ${style} — ${subset} */\n@font-face {${local}}\n`;
  }
  fs.writeFileSync(CSS_OUT, out);
  console.log(`Wrote ${count} woff2 (${(bytes / 1024).toFixed(0)} KB) + fonts.css`);
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
